icon: https://www.buzzing.cc/icon.png
favicon: https://www.buzzing.cc/favicon.ico
translations:
  "zh-Hans":
    "about_label": "关于此页面"
    "subscription_label": "订阅地址"
    "powered_by_label": "背后的人❤️"
    "languages_label": "该页面其他语言"
    "more_sites_label": "姊妹站点"
  "en":
    "about_label": "About this page"
    "subscription_label": "Subscription"
    "powered_by_label": "Made by ❤️"
    "languages_label": "Other languages"
    "more_sites_label": "More feeds"
  "ja":
    "about_label": "このページについて"
    "subscription_label": "購読"
    "powered_by_label": "製作者 ❤️"
    "languages_label": "他の言語"
    "more_sites_label": "他のフィード"
sites:
  devfeed:
    port: 8000
    test: true
    tags: []
    archive: false
    translations:
      "zh-Hans":
        title: "Reddit 热门"
        short_title: "Reddit 热门"
        description: "用中文浏览Reddit热门内容"
    sources:
      - url: https://www.reddit.com/r/all/top/.json?raw_json=1
        itemsPath: data.children
        type: reddit
        rules:
          - type: greaterEqual
            key: data.score
            value: "75000"
      # - url: https://hn.algolia.com/api/v1/search_by_date?tags=front_page&hitsPerPage=50
      #   itemsPath: hits
      #   type: hn
  hackernews:
    port: 8001
    tags:
      - hn
    translations:
      "zh-Hans":
        title: "Hacker News 首页"
        short_title: "HN首页"
        description: "用中文浏览Hacker News 首页最新文章"
        keywords: "HackerNews 头条, Hacker News 中文, Hacker News Story"
      "en":
        title: "Hacker News Front Page"
        short_title: "HN Front Page"
        description: "Hacker News Front Page Feed"
        keywords: "HackerNews 头条, Hacker News 中文, Hacker News Story"
    sources:
      - url: https://hn.algolia.com/api/v1/search_by_date?tags=front_page&hitsPerPage=50
        itemsPath: hits
        type: hn
  hn:
    port: 8002
    domain: prodhn.buzzing.cc
    tags:
      - hn
    translations:
      "zh-Hans":
        title: "Hacker News 热门"
        short_title: "HN热门"
        description: "追踪Hacker News上超过 200 points的帖子"
    sources:
      - url: http://hn.algolia.com/api/v1/search_by_date?tags=(story,poll,show_hn,ask_hn)&numericFilters=points>=200&hitsPerPage=50
        itemsPath: hits
        type: hn
  askhn:
    port: 8003
    domain: prodaskhn.buzzing.cc
    tags:
      - hn
    translations:
      "zh-Hans":
        title: "Hacker News 问答"
        short_title: "HN问答"
        description: "追踪 Hacker News 上的问答"
    sources:
      - url: https://hn.algolia.com/api/v1/search_by_date?tags=(ask_hn)&hitsPerPage=50
        itemsPath: hits
        type: hn
  showhn:
    port: 8004
    tags:
      - hn
    translations:
      "zh-Hans":
        title: "Show HN"
        short_title: "Show HN"
        description: "追踪 Hacker News 上的项目展示"
    sources:
      - url: https://hn.algolia.com/api/v1/search_by_date?tags=(show_hn)&hitsPerPage=50
        itemsPath: hits
        type: hn
  reddit:
    port: 8005
    tags:
      - reddit
    translations:
      "zh-Hans":
        title: "Reddit 热门"
        short_title: "Reddit 热门"
        description: "用中文浏览Reddit热门内容"
      "en":
        title: "Buzzing on Reddit"
        description: "See what's buzzing on Reddit in your native language"
        keywords: "Reddit Hot, Reddit Hot Feed"
    sources:
      - url: https://www.reddit.com/r/all/top/.json?raw_json=1
        itemsPath: data.children
        type: reddit
        rules:
          - type: greaterEqual
            key: data.score
            value: "75000"
archive:
  port: 9000
  siteIdentifier: i
  tags: []
