icon: https://www.buzzing.cc/icon.png
favicon: https://www.buzzing.cc/favicon.ico
root_domain: buzzing.cc
page_size: 200
translated_items_per_page: 100
max_files_per_site: -1
dev:
  max_files_per_site: 4
  translated_items_per_page: 2
languages:
  [
    { code: "zh-Hans", name: "简体中文", prefix: "" },
    { code: "zh-Hant", name: "繁体中文", prefix: "zh-Hant/" },
    { code: "en", name: "English", prefix: "en/" },
    { code: "ja", name: "日本語", prefix: "ja/" },
  ]
translations:
  zh-Hans:
    about_label: 关于此站
    subscription_label: 订阅地址
    powered_by_label: 背后的人❤️
    languages_label: 该页面其他语言
    more_sites_label: 姊妹站点
    tags_label: 所有标签
    archive_label: 历史归档
    issues_label: 往期精选
  en:
    about_label: About this page
    subscription_label: Subscription
    powered_by_label: Made by ❤️
    languages_label: Other languages
    more_sites_label: More feeds
    tags_label: All tags
    archive_label: Archive
    issues_label: Past issues
  ja:
    about_label: このページについて
    subscription_label: 購読
    powered_by_label: 製作者 ❤️
    languages_label: 他の言語
    more_sites_label: 他のフィード
    tags_label: すべてのタグ
    archive_label: アーカイブ
    issues_label: 過去の問題
archive:
  port: 9000
  siteIdentifier: i
  tags: []

sites:
  devfeed:
    redirect: true
    port: 8000
    test: true
    tags: []
    archive: false
    translations:
      "zh-Hans":
        title: "Reddit 热门"
        short_title: "Reddit 热门"
        description: "用中文浏览Reddit热门内容"
    sources:
      - url: https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en
        type: googlenews
        rules:
          - type: limit
            value: 2
  hackernews:
    port: 8001
    tags:
      - hn
    translations:
      "zh-Hans":
        title: "Hacker News 首页"
        short_title: "HN首页"
        description: "用中文浏览Hacker News 首页最新文章"
        keywords: "HackerNews 头条, Hacker News 中文, Hacker News Story"
      "en":
        title: "Hacker News Front Page"
        short_title: "HN Front Page"
        description: "Hacker News Front Page Feed"
        keywords: "HackerNews 头条, Hacker News 中文, Hacker News Story"
    sources:
      - url: https://hn.algolia.com/api/v1/search_by_date?tags=front_page&hitsPerPage=50
        itemsPath: hits
        type: hn
  hn:
    port: 8002
    domain: prodhn.buzzing.cc
    redirect: true
    tags:
      - hn
    translations:
      "zh-Hans":
        title: "Hacker News 热门"
        short_title: "HN热门"
        description: "追踪Hacker News上超过 200 points的帖子"
    sources:
      - url: http://hn.algolia.com/api/v1/search_by_date?tags=(story,poll,show_hn,ask_hn)&numericFilters=points>=200&hitsPerPage=50
        itemsPath: hits
        type: hn
  askhn:
    port: 8003
    domain: prodaskhn.buzzing.cc
    tags:
      - hn
    translations:
      "zh-Hans":
        title: "Hacker News 问答"
        short_title: "HN问答"
        description: "追踪 Hacker News 上的问答"
    sources:
      - url: https://hn.algolia.com/api/v1/search_by_date?tags=(ask_hn)&hitsPerPage=50
        itemsPath: hits
        type: hn
  showhn:
    port: 8004
    tags:
      - hn
    translations:
      "zh-Hans":
        title: "Show HN"
        short_title: "Show HN"
        description: "追踪 Hacker News 上的项目展示"
    sources:
      - url: https://hn.algolia.com/api/v1/search_by_date?tags=(show_hn)&hitsPerPage=50
        itemsPath: hits
        type: hn

  reddit:
    port: 8005
    redirect: true
    tags:
      - reddit
    translations:
      "zh-Hans":
        title: "Reddit 热门"
        short_title: "Reddit 热门"
        description: "用中文浏览Reddit热门内容"
      "en":
        title: "Buzzing on Reddit"
        description: "See what's buzzing on Reddit in your native language"
        keywords: "Reddit Hot, Reddit Hot Feed"
    sources:
      - url: https://www.reddit.com/r/all/top/.json?raw_json=1
        itemsPath: data.children
        type: reddit
        rules:
          - type: greaterEqual
            key: data.score
            value: "75000"
  news:
    port: 8006
    archive: true
    redirect: true
    tags:
      - news
    translations:
      "zh-Hans":
        title: "国外新闻头条 - 全球新闻头条 - 美国新闻头条"
        short_title: "国外新闻"
        description: "用中文浏览国外新闻头条，美国新闻头条，全球新闻(西方媒体)头条"
      "en":
        title: "Buzzing on World News"
        description: "See what's buzzing on the news in your native language"
        keywords: "Buzzing News, Buzzing News Feed"
    sources:
      - url: https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en
        type: googlenews
        rules:
          - type: limit
            value: 2
