icon: https://www.buzzing.cc/icon.png
favicon: https://www.buzzing.cc/favicon.ico
root_domain: buzzing.cc
page_size: 200
translated_items_per_page: 100
max_files_per_site: -1
dev:
  max_files_per_site: 4
  translated_items_per_page: 2
languages:
  [
    { code: "zh-Hans", name: "简体中文", prefix: "" },
    { code: "zh-Hant", name: "繁体中文", prefix: "zh-Hant/" },
    { code: "en", name: "English", prefix: "en/" },
    { code: "ja", name: "日本語", prefix: "ja/" },
  ]
translations:
  zh-Hans:
    about_label: 关于
    subscription_label: 订阅地址
    powered_by_label: 背后的人❤️
    languages_label: 该页面其他语言
    more_sites_label: 姊妹站点
    tags_label: 所有标签
    archive_label: 历史归档
    issues_label: 往期精选
    more_label: 更多
    less_label: 收起
    more_post_label: 好吧, 如果你还没看够... 以下👇
  en:
    about_label: About
    subscription_label: Subscription
    powered_by_label: Made by ❤️
    languages_label: Other languages
    more_sites_label: More feeds
    tags_label: All tags
    archive_label: Archive
    issues_label: Past issues
    more_label: More
    less_label: Less
  ja:
    about_label: このページについて
    subscription_label: 購読
    powered_by_label: 製作者 ❤️
    languages_label: 他の言語
    more_sites_label: 他のフィード
    tags_label: すべてのタグ
    archive_label: アーカイブ
    issues_label: 過去の問題
    more_label: もっと
    less_label: 閉じる
archive:
  port: 9000
  siteIdentifier: i
  tags: []

sites:
  devfeed:
    redirect: true
    port: 8000
    dev: true
    tags:
      - source-hackernews-index
    archive: false
    translations:
      "zh-Hans":
        title: "Reddit 热门"
        short_title: "Reddit 热门"
        description: "用中文浏览Reddit热门内容"

  hackernews:
    port: 8001
    tags:
      - hn
      - source-hackernews-index
    translations:
      "zh-Hans":
        title: "Hacker News 首页"
        short_title: "HN首页"
        description: "用中文浏览Hacker News 首页最新文章"
        keywords: "HackerNews 头条, Hacker News 中文, Hacker News Story"
      "en":
        title: "Hacker News Front Page"
        short_title: "HN Front Page"
        description: "Hacker News Front Page Feed"
        keywords: "HackerNews 头条, Hacker News 中文, Hacker News Story"

  hn:
    port: 8002
    domain: prodhn.buzzing.cc
    redirect: true
    tags:
      - hn
      - source-hackernews-best
    translations:
      "zh-Hans":
        title: "Hacker News 热门"
        short_title: "HN热门"
        description: "追踪Hacker News上超过 200 points的帖子"

  askhn:
    port: 8003
    domain: prodaskhn.buzzing.cc
    tags:
      - hn
      - source-hackernews-ask
    translations:
      "zh-Hans":
        title: "Hacker News 问答"
        short_title: "HN问答"
        description: "追踪 Hacker News 上的问答"

  showhn:
    port: 8004
    tags:
      - hn
      - source-hackernews-show
    translations:
      "zh-Hans":
        title: "Show HN"
        short_title: "Show HN"
        description: "追踪 Hacker News 上的项目展示"

  reddit:
    port: 8005
    redirect: true
    tags:
      - reddit
      - source-reddit-top
    translations:
      "zh-Hans":
        title: "Reddit 热门"
        short_title: "Reddit 热门"
        description: "用中文浏览Reddit热门内容"
      "en":
        title: "Buzzing on Reddit"
        description: "See what's buzzing on Reddit in your native language"
        keywords: "Reddit Hot, Reddit Hot Feed"

  ask:
    port: 8007
    redirect: true
    tags:
      - reddit
      - source-reddit-ask
    translations:
      "zh-Hans":
        title: "Reddit 热门提问"
        short_title: "Reddit提问"
        description: "用中文浏览 Reddit 上的热门提问"

  stocks:
    port: 8008
    redirect: true
    tags:
      - reddit
      - finance
      - source-reddit-stocks
      - source-twitter-stocks
      # - source-reddit-wallstreetbets
      # - source-reddit-bogleheads
    translations:
      "zh-Hans":
        title: "国外股市热门"
        description: "用中文浏览国外股票社区里的热门讨论"
  news:
    port: 8006
    archive: true
    redirect: true
    tags:
      - news
      - source-google-news
    translations:
      "zh-Hans":
        title: "国外新闻头条 - 全球新闻头条 - 美国新闻头条"
        short_title: "国外新闻"
        description: "用中文浏览国外新闻头条，美国新闻头条，全球新闻(西方媒体)头条"
      "en":
        title: "Buzzing on World News"
        description: "See what's buzzing on the news in your native language"
        keywords: "Buzzing News, Buzzing News Feed"
  ph:
    port: 8009
    archive: true
    redirect: true
    tags:
      - tech
      - source-producthunt-top
    translations:
      "zh-Hans":
        title: "Product Hunt"
        short_title: "国外新闻"
        description: "用中文浏览国外新闻头条，美国新闻头条，全球新闻(西方媒体)头条"
      "en":
        title: "Buzzing on World News"
        description: "See what's buzzing on the news in your native language"
        keywords: "Buzzing News, Buzzing News Feed"
  crypto:
    port: 8010
    archive: true
    redirect: true
    tags:
      - tech
      - source-crypto-reddit
      - source-crypto-twitter
    translations:
      "zh-Hans":
        title: "加密货币热门讨论"
        short_title: "加密货币"
        description: "加密货币热门讨论"
  dev:
    port: 8011
    archive: true
    redirect: true
    tags:
      - tech
      - source-devto
    translations:
      "zh-Hans":
        title: "开发者热门讨论"
        short_title: "开发者"
        description: "开发者热门讨论"
  quora:
    port: 8012
    archive: true
    redirect: true
    tags:
      - ask
      - source-quora
    translations:
      "zh-Hans":
        title: "Quora 热门问答"
        short_title: "Quora热门"
        description: "Quora 热门问答"
  depth:
    port: 8013
    archive: true
    redirect: true
    tags:
      - depth
      - source-reddit-depth
    translations:
      "zh-Hans":
        title: "深度文章分享"
        short_title: "深度思考"
        description: "Reddit 精神食粮小组"
  nytimes:
    port: 8014
    archive: true
    redirect: true
    tags:
      - depth
      - news
      - source-twitter-nytimes
    translations:
      "zh-Hans":
        title: "纽约时报热门文章"
        short_title: "纽约时报"
        description: "纽约时报热门文章"
  wsj:
    port: 8015
    archive: true
    redirect: true
    tags:
      - depth
      - news
      - source-twitter-wsj
    translations:
      "zh-Hans":
        title: "华尔街日报热门文章"
        short_title: "华尔街日报"
        description: "华尔街日报热门文章"
  economist:
    port: 8016
    archive: true
    redirect: true
    tags:
      - depth
      - news
      - source-twitter-economist
    translations:
      "zh-Hans":
        title: "经济学人热门文章"
        short_title: "经济学人"
        description: "经济学人热门文章"
  sideproject:
    port: 8017
    archive: true
    redirect: true
    tags:
      - sideproject
      - source-reddit-sideproject
    translations:
      "zh-Hans":
        title: "业余项目分享交流"
        short_title: "业余项目"
        description: "Reddit 业余项目小组"
sources:
  - url: https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en
    type: googlenews
    id: source-google-news
    rules:
      - type: limit
        value: "2"
  - url: https://hn.algolia.com/api/v1/search_by_date?tags=front_page&hitsPerPage=50
    type: hn
    id: source-hackernews-index
  - url: http://hn.algolia.com/api/v1/search_by_date?tags=(story,poll,show_hn,ask_hn)&numericFilters=points>=200&hitsPerPage=50
    type: hn
    id: source-hackernews-best
  - url: https://hn.algolia.com/api/v1/search_by_date?tags=(ask_hn)&hitsPerPage=50
    type: hn
    id: source-hackernews-ask
  - url: https://hn.algolia.com/api/v1/search_by_date?tags=(show_hn)&hitsPerPage=50
    type: hn
    id: source-hackernews-show
  - url: https://www.reddit.com/r/all/top/.json?raw_json=1
    type: reddit
    id: source-reddit-top
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "85000"
  - url: https://www.reddit.com/r/AskReddit/top/.json?raw_json=1
    type: reddit
    id: source-reddit-ask
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "70000"
  - url:
      - https://www.reddit.com/r/TooAfraidToAsk/top/.json?raw_json=1
      - https://www.reddit.com/r/NoStupidQuestions/top/.json?raw_json=1
    type: reddit
    id: source-reddit-ask
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "45000"
  - url:
      - https://www.reddit.com/r/Ask_Politics/top/.json?raw_json=1
      - https://www.reddit.com/r/AskHistorians/top/.json?raw_json=1
      - https://www.reddit.com/r/AskWomen/top/.json?raw_json=1
      - https://www.reddit.com/r/TrueAskReddit/top/.json?raw_json=1
      - https://www.reddit.com/r/askscience/top/.json?raw_json=1
      - https://www.reddit.com/r/askphilosophy/top/.json?raw_json=1
    id: source-reddit-ask
    type: reddit
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "300"

  - url: https://www.reddit.com/r/wallstreetbets/top/.json?raw_json=1
    type: reddit
    id: source-reddit-wallstreetbets
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "4000"
  - url: https://www.reddit.com/r/Bogleheads/top/.json?raw_json=1
    type: reddit
    id: source-reddit-bogleheads
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "15"
  - url:
      - https://www.reddit.com/r/stocks/top/.json?raw_json=1
      - https://www.reddit.com/r/investing/top/.json?raw_json=1
    type: reddit
    id: source-reddit-stocks
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "40"
  - id: source-producthunt-top
    url: https://api.producthunt.com/v2/api/graphql
    type: ph
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "60"
  - id: source-crypto-reddit
    url:
      - https://www.reddit.com/r/CryptoCurrency/top/.json?raw_json=1
      - https://www.reddit.com/r/Bitcoin/top/.json?raw_json=1
    type: reddit
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "400"

  - url: https://dev.to/api/articles?top=3
    id: source-devto
    type: devto
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "40"

  - url: https://www.reddit.com/r/SideProject/top/.json?raw_json=1
    id: source-reddit-sideproject
    type: reddit
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "4"
  - url:
      - https://www.reddit.com/r/TrueReddit/top/.json?raw_json=1
      - https://www.reddit.com/r/Foodforthought/top/.json?raw_json=1
    id: source-reddit-depth
    type: reddit
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "50"
  - url: nytimes
    params:
      include_rts: false
    id: source-twitter-nytimes
    type: twitter
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "1000"
  - url: wsj
    params:
      include_rts: false
    id: source-twitter-wsj
    type: twitter
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "150"
  - url: TheEconomist
    params:
      include_rts: false
    id: source-twitter-economist
    type: twitter
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "150"
  - url:
      - charliebilello
      - Stocktwits
      - MarketWatch
      - The_Real_Fly
      - awealthofcs
      - michaelbatnick
      - InvestmentTalkk
    type: twitter
    id: source-twitter-stocks
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "400"
  - url:
      - s2fmultiple
    type: twitter
    id: source-crypto-twitter
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "200"
  - url:
      - 100trillionUSD
    type: twitter
    id: source-crypto-twitter
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "3000"
  - url: Quora
    params:
      include_rts: false
    id: source-quora
    type: twitter
    rules:
      - type: include
        key: getTitle
        value: "?"
