name: cron tasks
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      force_all:
        default: "0"
        description: "Force all sites to build"
        type: string
      translate_count:
        description: "translate count"
        required: false
        default: "-1"
      translate_timeout:
        description: "translate timeout in minutes"
        required: false
        default: "120"
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install wrangler
        run: npm install -g wrangler
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
      - run: make prod-load
        env:
          R2_ACCESS_KEY_ID: ${{secrets.R2_ACCESS_KEY_ID}}
          R2_SECRET_ACCESS_KEY: ${{secrets.R2_SECRET_ACCESS_KEY}}
          R2_REGION: ${{secrets.R2_REGION}}
          R2_ENDPOINT: ${{secrets.R2_ENDPOINT}}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
      - run: make install
      - run: make prod-source
        id: source
        continue-on-error: true
        env:
          ARCHIVE_ACCESS_KEY_ID: ${{secrets.ARCHIVE_ACCESS_KEY_ID}}
          ARCHIVE_SECRET_ACCESS_KEY: ${{secrets.ARCHIVE_SECRET_ACCESS_KEY}}
          ARCHIVE_ENDPOINT: ${{secrets.ARCHIVE_ENDPOINT}}
          ARCHIVE_REGION: ${{secrets.ARCHIVE_REGION}}
          TWITTER_BEARER_TOKEN: ${{secrets.TWITTER_BEARER_TOKEN}}
          TWITTER_ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}
          TWITTER_ACCESS_TOKEN_SECRET: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
          TWITTER_CONSUMER_SECRET: ${{secrets.TWITTER_CONSUMER_SECRET}}
          PRODUCTHUNT_TOKEN: ${{secrets.PRODUCTHUNT_TOKEN}}
          TRANSLATE_COUNT: ${{ github.event.inputs.translate_count }}
          TRANSLATE_TIMEOUT: ${{ github.event.inputs.translate_timeout }}
          ALL: ${{ github.event_name=='push' && '1' ||  github.event.inputs.force_all }}
      - name: upload files
        run: make prod-upload
        env:
          R2_ACCESS_KEY_ID: ${{secrets.R2_ACCESS_KEY_ID}}
          R2_SECRET_ACCESS_KEY: ${{secrets.R2_SECRET_ACCESS_KEY}}
          R2_REGION: ${{secrets.R2_REGION}}
          R2_ENDPOINT: ${{secrets.R2_ENDPOINT}}
          ARCHIVE_ACCESS_KEY_ID: ${{secrets.ARCHIVE_ACCESS_KEY_ID}}
          ARCHIVE_SECRET_ACCESS_KEY: ${{secrets.ARCHIVE_SECRET_ACCESS_KEY}}
          ARCHIVE_ENDPOINT: ${{secrets.ARCHIVE_ENDPOINT}}
          ARCHIVE_REGION: ${{secrets.ARCHIVE_REGION}}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
          AWS_ACCESS_KEY_ID: ${{ secrets.ARCHIVE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARCHIVE_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{secrets.ARCHIVE_REGION}}
          DUFS_URL: ${{secrets.DUFS_URL}}
          DUFS_SECRETS: ${{secrets.DUFS_SECRETS}}
      - name: upload temp folder to github action for debug
        uses: actions/upload-artifact@v3
        with:
          name: tempt
          path: temp
          if-no-files-found: ignore
      - name: throw if source failed
        if: steps.source.outcome == 'failure'
        run: |
          echo "::error::Source build failed"
          exit 1
      - name: Publish pages
        if: true
        run: make prod-publish
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
