name: pre release
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: pre-release
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install wrangler
        run: npm install -g wrangler
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*deps.ts') }}
      - run: make test
      - run: make prod-load
        env:
          R2_ACCESS_KEY_ID: ${{secrets.R2_ACCESS_KEY_ID}}
          R2_SECRET_ACCESS_KEY: ${{secrets.R2_SECRET_ACCESS_KEY}}
          R2_REGION: ${{secrets.R2_REGION}}
          R2_ENDPOINT: ${{secrets.R2_ENDPOINT}}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
      - name: Build Site
        run: make prod-build
      - name: zip current folder
        run: zip -r -q current.zip ./current
      - name: zip public folder
        run: zip -r -q public.zip public
      - name: Upload public, current to release assets
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-${{ env.NOW }}"
          prerelease: true
          title: "Development Build"
          files: |
            current.zip
            public.zip
