name: upload archive
on:
  repository_dispatch:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "*/15 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.ARCHIVE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ARCHIVE_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.ARCHIVE_REGION}}
      - name: create test files
        run: |
          mkdir -p archive
          echo "hello world" > archive/hello.txt
          echo "hello world" > archive/hello2.txt
      - name: upload files
        run: make prod-awsuploadarchive
