name: upload archive
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "*/15 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: upload-archive
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: create test files
        run: |
          mkdir -p archive
          echo "hello world" > archive/hello.txt
          echo "hello world" > archive/hello2.txt
      # - uses: isbang/setup-awscli@v0.1.0
      # - run: make prod-awsuploadarchive
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      #     AWS_ENDPOINT: ${{secrets.AWS_ENDPOINT}}
      - run: make prod-uploadarchive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_ENDPOINT: ${{secrets.AWS_ENDPOINT}}
