name: upload archive
on:
  repository_dispatch:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "*/15 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
      - name: download archive zip file
        run: wget http://bashupload.com/bVpT7/archive.zip
      - name: unzip archive.zip
        run: unzip -o -q archive.zip
      - name: upload files
        run: make prod-uploadarchive
        env:
          R2_ACCESS_KEY_ID: ${{secrets.R2_ACCESS_KEY_ID}}
          R2_SECRET_ACCESS_KEY: ${{secrets.R2_SECRET_ACCESS_KEY}}
          R2_REGION: ${{secrets.R2_REGION}}
          R2_ENDPOINT: ${{secrets.R2_ENDPOINT}}
          ARCHIVE_ACCESS_KEY_ID: ${{secrets.ARCHIVE_ACCESS_KEY_ID}}
          ARCHIVE_SECRET_ACCESS_KEY: ${{secrets.ARCHIVE_SECRET_ACCESS_KEY}}
          ARCHIVE_ENDPOINT: ${{secrets.ARCHIVE_ENDPOINT}}
          ARCHIVE_REGION: ${{secrets.ARCHIVE_REGION}}
          CLOUDFLARE_API_TOKEN: ${{secrets.CF_API_TOKEN}}
